### ISSUE TITLE
Java script directly use GeoScript

### ISSUE THREAD

**Issue by Chris938621** [jericks/geometrycommands#1]
It was not possible to ask support.
I tried to run your libary in my Javscript envoirement but this does't success. I get error that required.js has a problem errors by importing proj.js. Starting call was

 var geom = require("geoscript/geom");

May you send me an envoriement to use your engine in my js files directly?
Mail:
account: schmidt.christian 
provider: Aol.de

Best regards
Chris

**Comment by Chris938621** [comment]
wrong section

**Comment by jericks** [comment]
I think you are looking for the GeoScript JavaScript project:

https://github.com/geoscript/geoscript-js

Cheers,
Jared

**Comment by Chris938621** [comment]
Hello Jared,
thanks a lot!
However the project does not run, may you send me a minimal exampe of including the project with required.js ?
Best regards,
Chris

Christian Schmidt

[Beschreibung: HHN_E-Mail_200px]
Zentrum für virtuelle Patienten (CAMPUS): http://www.virtuelle-patienten.de

Hochschule Heilbronn
Heilbronn University
Max-Planck-Str. 39
D-74081 Heilbronn

E-mail: christian.schmidt@hs-heilbronn.de
